services:
  mysql:
    image: mysql:8.0
    container_name: mahjong-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mahjong
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:   # WebでDBを確認できるツール
    image: adminer
    container_name: mahjong-adminer
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
