spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mahjong
      ?useSSL=false
      &allowPublicKeyRetrieval=true
      &characterEncoding=utf8
      &serverTimezone=Asia/Tokyo
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: none
  # ログ見やすさ（任意）
  jdbc:
    template:
      query-timeout: 5

server:
  port: 8080
